# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
extends:
  - 'slekup'
parserOptions:
  project:
    - './tsconfig.json'
    # - './example/tsconfig.json'
rules:
  'no-console': 'off'
